### ISSUE TITLE
If then else

### ISSUE THREAD

**Issue by RobinKnipe** [Alex-Swann/acp-vpn-bash#1]
https://github.com/Alex-Swann/acp-vpn-bash/blob/cdba214592b8ece68e488b68b1e2a315d09b1668/acp_vpn.sh#L172-L177

I think you could benefit from using `elif` here (and on the subsequent checks for `$1`).

Also I note you're using inline ifs, e.g. `if [[ condition ]] ; then do-something ; fi` - you might like to consider a shorthand version:
```shell
[ condition ] && do-something
```
... you can even do ternaries:
```shell
[ condition ] && do-something || something-else
```

**Comment by Alex-Swann** [comment]
Cheers Robin. Hadn't even spotted these issues till today. I've refactored those conditionals thanks. I tried to do the shorthand and it did something weird. It's likely those inlines were segments copied over from Stack Overflow answers to bash questions just to get something working. Haven't got time to dig into it (because it works lol), but of course, yeah makes sense. I'll see if I can get shorthands working in a later commit. Will resolve this for now though. Thanks
